# Generated by Django 6.0.3 on 2026-03-24 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultaMed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='ap_materno',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='ap_paterno',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='matricula_clinica',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nombres',
            field=models.CharField(max_length=50),
        ),
    ]
