# Generated by Django 6.0.3 on 2026-03-25 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultaMed', '0002_paciente_sexo_alter_paciente_ap_materno_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consulta',
            old_name='plan_accion',
            new_name='plan_de_accion',
        ),
    ]
